version: '3'

services:
    
    iframely-service:
        hostname: iframely-service.net
        image: joelabair/iframely:latest
        environment:
            - PORT=8061
            - HOST=0.0.0.0
            - NODE_FORKS=2
        build:
            context: ./
