version: '3'

networks:
    sendsitesnet:
        external: true

services:
    
    iframely-service:
        hostname: iframely-service.net
        image: joelabair/iframely:latest
        build: .
        ports:
          - 8061
        networks:
            sendsitesnet:
